version: '3.2'

services:
  freeradius:
    image: "final:latest"
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - "./freeradius:/etc/freeradius"
      - "./freeradius:/etc/raddb"
    environment:
      - DB_NAME=cache_example
      - DB_HOST=172.16.205.1
      - DB_USER=radius
      - DB_PASS=radtest
      - DB_PORT=3306
      - SMTP_SERVER=smtp.i.ua
      - SMTP_PORT=465
      - SMTP_USER=myradius@i.ua
      - SMTP_PASS=testpass
      - SMTP_ADMIN_EMAIL=tkramarets@gmail.com
      - SMTP_SENDER_EMAIL=myradius@i.ua
      - SMTP_SUBJECT=test
      - CACHE_TIME=5
      - IMAP_URI=smtps://smtp.gmail.com
      - IMAP_TIMEOUT=5s
      - RAD_DEBUG=yes
      - RAD_DEBUG_LEVEL=-X
    restart: always
    networks:
      - backend

networks:
  backend:
    ipam:
      config:
        - subnet: 10.0.0.0/24
